### ISSUE TITLE
This tool made me wait .006 seconds without a reason

### ISSUE THREAD

**Issue by roadelou** [theodumont/video-logging#1]
In the [src/video-loggin.py](https://github.com/theodumont/video-logging/blob/master/src/video_logging.py) file, in the folder_sort and trash_videos functions, the for loops have an unexplained sleep time :

```python3
for file in os.listdir():
      time.sleep(.001)
```

I guess this is an aesthetic thing for the progress bar, but it might be worth _putting a comment_ to explain it, else this looks very surprising.

**Comment by theodumont** [comment]
Sure, should have put a comment to explain this! It is only needed in `trash_videos`, when checking the duration of the files. When I do not wait each time, errors are raised, maybe because files are opened and closed too fast?

Anyway, I deleted the useless instances and put a comment in `trash_videos`.

**Comment by roadelou** [comment]
I tried removing the time.sleep, but I cannot reproduce the bug with trash_videos.

One note though : __waiting an arbitrary amount of time__ to make a bug disappear should only be used as a __last resort__. I imagine that you tried solving it another way but did not succeed and that is why you put a sleep here. Sometimes (especially if the bug comes from another library) it cannot be avoided, but 90% of the time you should wait __for something__ to solve the bug.

I trust that you already knows what I wrote below, but I do have to put my markdown to use or I might get rusty :laughing:

The reason to avoid that practice is quite obvious : If the bug occurs because a specific action takes some time to complete, then the amount of time that the action takes will __vary a little between runs__. In the worst case, that can manifest itself as a bug that appears sometimes, for reasons seemingly unrelated to your code (the best kind of bugs, as everyone knows :smile:).

Another thing that makes sleep frowned upon is that the computer used for development and the one used for production can have widely __different hardware__ (and OS), hence the amount of time that made the bug disappear in development might be too small (or absurdly too large) for production. This means you might end up with __random bugs__ in production (or on the users computer) that just never appear in development.

Hence, it is best practice to _investigate what causes your bug_ and find out what you are really waiting for.

Then again, not everything has to be Fort Nox :wink:
