### ISSUE TITLE
Tests for None are too broad

### ISSUE THREAD

**Issue by roadelou** [theodumont/video-logging#3]
At various points in the [src/video-logging.py](https://github.com/theodumont/video-logging/blob/master/src/video_logging.py) file, the functions will check if their directory argument is None. The current implementation is :

```python
if directory:
  # Do things if directory is not None
  pass

# Or its negative counterpart
if not directory:
  pass
```

But this pattern, aside from not being completely obvious, __will also match a lot of things that are not None__. The negative variant variant is the most problematic one I think :

```python
# not ... will match None
print(not bool(None))

# It will of course also match False
print(not bool(False))

# And, as expected, 0
print(not bool(0))

# More surprising, this will also match an empty list
print(not bool([]))

# While we are at it, it also matches an empty dictionary
print(not bool({}))

# More problematic, it also matches an empty string
print(not bool(''))
```

While those things are usually not a huge issue, there is a __very simple and solid workaround__ in python to test if directory is not None :

```python
if directory is not None:
  # anticlimactic, is it not ?
  pass

# The positive variant
if directory is None:
  pass
```

Aside from being safer and more explicit, this will also avoid issues where __python does not do what English suggests it does__. For instance in sort_by_date :

```python
if directory and extension in EXTENSIONS[directory]:
  # Code follows
```

Which reads in English as :

> if directory and extension [both are] in EXTENSIONS[directory]

But in fact for python it means (in this context) :

> if directory is not None and extension in EXTENSIONS[directory]

Note that the expression is __used correctly in sort_by_date__, I am just pointing out that this can be tricky when reading the code.

**Comment by theodumont** [comment]
Thank you for the detailed issue!
Indeed, it may be less tricky to read now.
