### ISSUE TITLE
Ternary operator looking for some love

### ISSUE THREAD

**Issue by roadelou** [theodumont/video-logging#6]
In the trash_videos functions of [src/video_logging.py](https://github.com/theodumont/video-logging/blob/master/src/video_logging.py), near the end of the function, you have implemented the 's' for plural as :

```python
term = 's' * (nb_trashed >= 2)
```

I think that what you are intending to use here is a __ternary operator__, which can be implemented in python (>= 2.5) with :

```python
term = "s" if nb_trashed >= 2 else ""
```

While it is indeed longer to type, the purpose of the line should be more obvious to the reader :smile:

**Comment by theodumont** [comment]
Yes indeed! Thank you, it's much more readable now.
